### ISSUE TITLE
Discord Link in readme is broken

### ISSUE THREAD

**Issue by silasary** [herbertmilhomme/PokemonUnity#11]
The README in `gh-pages` points at https://discord.gg/SggHcXP, which is apparently a dead link.

**Comment by herbertmilhomme** [comment]
Sorry, that was written quite a while ago. I'm no longer a part of that discord community and not sure how to locate it.

The original repository that is supposed to be used by the main server isn't even active anymore so they don't bother to update the link there either. Honestly, that community is a lost cause. They're working on redoing the project but don't communicate anything in the discord and their new git is private and secret. 

Good luck finding them, but I'm kinda on my own if you're looking to chat with me, you can find me on someone else's git: https://discord.gg/ZECFmYA

Or you can find me privately: `1201#FlakFlayster`
